# Generated by Django 4.1.3 on 2024-05-18 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAccountTable',
            fields=[
                ('group_account_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(blank=True, max_length=200, null=True)),
                ('account_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('payment', models.IntegerField(blank=True, null=True)),
                ('flag', models.IntegerField()),
            ],
            options={
                'db_table': 'group_account_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupCategoryTable',
            fields=[
                ('group_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=200)),
                ('transaction_type', models.CharField(blank=True, max_length=45, null=True)),
                ('category_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'group_category_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupTable',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=200)),
                ('group_code', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'group_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalAccountTable',
            fields=[
                ('personal_account_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(blank=True, max_length=200, null=True)),
                ('account_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('payment', models.IntegerField(blank=True, null=True)),
                ('flag', models.IntegerField()),
            ],
            options={
                'db_table': 'personal_account_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalCategoryTable',
            fields=[
                ('personal_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=45)),
                ('transaction_type', models.CharField(blank=True, max_length=200, null=True)),
                ('category_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'personal_category_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalTable',
            fields=[
                ('personal_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'personal_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SplitTable',
            fields=[
                ('split_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment', models.IntegerField(blank=True, null=True)),
                ('advance_payment', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'split_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalGroupLinkingTable',
            fields=[
                ('personal', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='line_bot_app.personaltable')),
            ],
            options={
                'db_table': 'personal_group_linking_table',
                'managed': False,
            },
        ),
    ]
